#  settings for your test runner - you control things like what markers exist, where to find tests, and what options to always apply.
[pytest]
markers =
    smoke: critical path tests
    regression: full regression suite
    visual: visual regression tests
    mobile: mobile emulation tests
#addopts =--reruns 2 --reruns-delay 1